import express from 'express';
import cors from 'cors';
import cookieSession from 'cookie-session';
import passport from 'passport';
import dotenv from 'dotenv';
import swaggerUi from 'swagger-ui-express';

import { connectMongo } from './db/mongoose.js';
import authRoutes from './routes/auth.js';
import adventurersRoutes from './routes/adventurers.js';
import campaignsRoutes from './routes/campaigns.js';
import { notFound, errorHandler } from './middleware/errorHandler.js';

dotenv.config();

// 1) CREATE APP FIRST
const app = express();

// 2) CORE MIDDLEWARE
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(cors({ origin: (process.env.CORS_ORIGIN || '*').split(','), credentials: true }));
app.use(cookieSession({
  name: 'session',
  keys: [process.env.COOKIE_KEY || 'fallback_key'],
  maxAge: 10 * 60 * 1000
}));
app.use(passport.initialize());
app.use(passport.session());

// 3) SWAGGER (Swagger 2.0 via swagger-autogen)
import { readFileSync, existsSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Always use the OAS2 file generated by swagger.js
const SWAGGER_FILE = path.join(__dirname, 'swagger-output.json');

let swaggerDoc;
if (existsSync(SWAGGER_FILE)) {
  swaggerDoc = JSON.parse(readFileSync(SWAGGER_FILE, 'utf8'));
} else {
  // OAS2 fallback so /docs stays up even before generation
  const isProd = process.env.NODE_ENV === 'production';
  swaggerDoc = {
    swagger: '2.0',
    info: { title: 'Adventurer’s Guild API', description: 'API for managing D&D adventurers', version: '1.0.0' },
    host: isProd ? 'fall2025.onrender.com' : 'localhost:8080',
    basePath: '/',
    schemes: [isProd ? 'https' : 'http'],
    securityDefinitions: {
      bearerAuth: { type: 'apiKey', in: 'header', name: 'Authorization', description: 'Use: Bearer <JWT>' }
    },
    security: [{ bearerAuth: [] }],
    paths: {}
  };
}

app.use('/docs', swaggerUi.serve, swaggerUi.setup(swaggerDoc));


// 4) HEALTH
// #swagger.tags = ['Health']
// #swagger.summary = 'Liveness probe'
app.get('/healthz', (_req, res) => res.json({ ok: true }));


// 5) ROUTES
app.use('/auth', authRoutes);
app.use('/adventurers', adventurersRoutes);
app.use('/campaigns', campaignsRoutes);

// 6) 404 + ERROR HANDLER
app.use(notFound);
app.use(errorHandler);

// 7) START AFTER DB CONNECTS
const PORT = process.env.PORT || 8080;
connectMongo()
  .then(() => app.listen(PORT, () => console.log(`✅ API on http://localhost:${PORT}`)))
  .catch((err) => {
    console.error('❌ Mongo connection failed:', err);
    process.exit(1);
  });
